services:

  app:
    image: invoice
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: invoice

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: invoice