version: "2.12.0"


services:

  invoice:
    build: .

    ports:
      - 8000:8000

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: invoice

  db:
    image: postgres:14.5-alpine3.16

    volumes:
      - dbdata:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: invoice