version: "2.12.0"

services:
  invoice:
    image: profiles:v1
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:15.1-alpine3.16
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lesavant
      POSTGRES_PASSWORD: 22091431
      POSTGRES_DB: profiles

volumes:
  dbdata: